1671 task110 database storage
Sanaiqbal-dev/portfolio-project-react pull request #10
Opened 2023-12-12 09:09 UTC by Sanaiqbal-dev

Task related to saving user's portfolio data in database, and adding appropriate CRUD operations, is completed. Here is the link to user story:
https://dev.azure.com/CodeNinjaConsulting/Talent%20Pool/_workitems/edit/1606

2023-12-13 08:03 UTC, huzaifah0x00 requested changes
Added some comments.
Please address those in all places where applicable, I've only added a comment on one location where I find an issue.

2023-12-13 08:03 UTC, huzaifah0x00 commented on portfolio-project-react/server/routes/route.js
> +  upload.single("testImage"),
It's an important security practice to limit the maximum file size to something, otherwise some malicious user could upload a 100gb file as their profile picture, and that could crash your system or cost you money ( e.g if you use cloud storage e.g aws )

not sure if multer has a filesize limit by default, in which case, please ignore this comment

2023-12-13 08:03 UTC, huzaifah0x00 commented on portfolio-project-react/src/components/About/About.jsx
> +  const [id, setId] = useState("");
why is the id a separate state? isn't the id just part of the aboutContent already? we can use aboutContent._id

2023-12-13 08:03 UTC, huzaifah0x00 commented on portfolio-project-react/src/components/About/About.jsx
> +        setEmail(jsonData[0].email);
instead of having separate states for all of these, its better to just have a single object as a state, that has all of these properties. as they're part of the same object. 

then you can probably just do setAboutData(jsonData[0])

2023-12-13 08:03 UTC, huzaifah0x00 commented on portfolio-project-react/src/components/Details/Details.jsx
>    );
Avoid duplicating state when you can derive the filtered state from an existing state.

e.g in this case you can use useMemo and searchText to create a filteredWorkExperienceList variable, without another useState.

for example, something like:
```tsx
const filteredWorkExperienceList = useMemo(() => original.filter((e) => e.name.includes(searchTerm), [original, searchTerm]));
```

the reason to avoid useState here is that it gets more complicated to call `setFilteredWorkExperienceList` in case the originalWorkExperienceList is updated. that will make the code more complicated and cause bugs where your filtered items won't be based on the latest original array.

2023-12-13 08:03 UTC, huzaifah0x00 commented on portfolio-project-react/src/components/About/About.jsx
> +  }, [isEditModeEnabled]);
[question] what's the purpose of this?

2023-12-13 08:04 UTC, huzaifah0x00 commented
I'd recommend going through https://react.dev/learn/managing-state, and https://react.dev/learn/choosing-the-state-structure if you get time

2023-12-14 11:02 UTC, Sanaiqbal-dev commented on portfolio-project-react/src/components/About/About.jsx
> +  }, [isEditModeEnabled]);
So I had to handle a situation, where I needed to update the information in database only when edit mode is changed to save state and there is a change in the content, for that I added this code section.

2023-12-14 12:11 UTC, huzaifah0x00 approved these changes
Looks good

2023-12-14 12:12 UTC, merged